//how web works 
//user = > browser => enter url => website comes 
//behind the scenes 
//its either stored on a server or generated by server 
//how does server know that we call it 
//adress of server is in ip 
//when u enter url your browser calls a dns server where domains are mapped to ip 
//when u enter the url that is called a request 
//request can include type of req like use for getting something storing something can contain metadeta
//what u get back is response u can get meta data etc and html code 
//In web apps, data is often transferred instead of full HTML pages. APIs return structured data (like JSON or XML) that the frontend processes
//what u see on web is result of html css js 
//html for structure css for style js for logic and interactivity
//all this data tramfer is standardadasided by http and happends over tcp/ip 
//hyper text transfer protocol / secure HTTP defines how clients and servers should communicate, but the actual transfer is handled by lower-level protocols like TCP.
//https is http just encyrptyed uses tls for encryption 
//http is just what data transfer should look like it is rules 
//but also in apps data is tranfered not html stuff but some data is tranffered 
//req and response is same but for example mobile app call for json/xml
